import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: {
    relative: true,
    files: ["./index.html", "./src/**/*.{ts,tsx}"],
  },
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "surface-lowest": "rgb(var(--color-surface-lowest) / <alpha-value>)",
        "surface-low": "rgb(var(--color-surface-low) / <alpha-value>)",
        "surface-card": "rgb(var(--color-surface-card) / <alpha-value>)",
        "surface-high": "rgb(var(--color-surface-high) / <alpha-value>)",
        "surface-highest": "rgb(var(--color-surface-highest) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        outline: "rgb(var(--color-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-strong": "rgb(var(--color-primary-strong) / <alpha-value>)",
        "status-update": "rgb(var(--color-status-update) / <alpha-value>)",
        "status-create": "rgb(var(--color-status-create) / <alpha-value>)",
        "status-remove": "rgb(var(--color-status-remove) / <alpha-value>)",
        "status-conflict": "rgb(var(--color-status-conflict) / <alpha-value>)",
        "theme-card": "rgb(var(--theme-card-bg) / <alpha-value>)",
        "theme-card-border": "rgb(var(--theme-card-border) / <alpha-value>)",
        "theme-card-header": "rgb(var(--theme-card-header) / <alpha-value>)",
        "theme-control": "rgb(var(--theme-control-bg) / <alpha-value>)",
        "theme-control-hover": "rgb(var(--theme-control-hover) / <alpha-value>)",
        "theme-control-border": "rgb(var(--theme-control-border) / <alpha-value>)",
        "theme-control-fg": "rgb(var(--theme-control-fg) / <alpha-value>)",
        "theme-button-primary": "rgb(var(--theme-button-primary-bg) / <alpha-value>)",
        "theme-button-primary-hover": "rgb(var(--theme-button-primary-hover) / <alpha-value>)",
        "theme-button-primary-fg": "rgb(var(--theme-button-primary-fg) / <alpha-value>)",
        "theme-nav": "rgb(var(--theme-nav-bg) / <alpha-value>)",
        "theme-nav-hover": "rgb(var(--theme-nav-hover) / <alpha-value>)",
        "theme-nav-active": "rgb(var(--theme-nav-active) / <alpha-value>)",
        "theme-nav-active-fg": "rgb(var(--theme-nav-active-fg) / <alpha-value>)",
        "theme-nav-active-border": "rgb(var(--theme-nav-active-border) / <alpha-value>)",
        "theme-subnav": "rgb(var(--theme-subnav-bg) / <alpha-value>)",
        "theme-toolbar": "rgb(var(--theme-toolbar-bg) / <alpha-value>)",
        "theme-switch": "rgb(var(--theme-switch-bg) / <alpha-value>)",
        "theme-switch-thumb": "rgb(var(--theme-switch-thumb) / <alpha-value>)",
        "theme-switch-checked": "rgb(var(--theme-switch-checked) / <alpha-value>)",
        "theme-switch-checked-thumb": "rgb(var(--theme-switch-checked-thumb) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "sidebar-width": "64px",
      },
      fontFamily: {
        sans: ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-md": ["13px", { lineHeight: "18px", fontWeight: "450" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        h2: ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
      boxShadow: {
        glow: "0 14px 28px rgb(var(--theme-glow) / 0.22)",
      },
    },
  },
  plugins: [],
} satisfies Config;
