//! Generated by scripts/gen-surface-matrix.py; do not edit by hand.

#![allow(dead_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct SurfaceMapping {
    pub(crate) canonical_method: &'static str,
    pub(crate) tauri_command: Option<&'static str>,
    pub(crate) note: Option<&'static str>,
}

pub(crate) static SURFACE_MAPPINGS: &[SurfaceMapping] = &[
    SurfaceMapping {
        canonical_method: "agent.catalog.list",
        tauri_command: Some("list_agent_catalog"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.connection.check",
        tauri_command: Some("check_agent_connection"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.disable",
        tauri_command: Some("disable_agent"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.enable",
        tauri_command: Some("enable_agent"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.install.preview",
        tauri_command: Some("preview_agent_installation"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.install.run",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "agent.installed.get",
        tauri_command: Some("get_installed_agent"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.installed.list",
        tauri_command: Some("list_installed_agents"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.market.inspect",
        tauri_command: Some("inspect_agent_market_item"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.market.list",
        tauri_command: Some("list_agent_market"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.market.refresh.run",
        tauri_command: Some("refresh_agent_market"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.models.list",
        tauri_command: Some("list_agent_models"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.runtime.check",
        tauri_command: Some("check_agent_runtime"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.uninstall.preview",
        tauri_command: Some("preview_agent_uninstall"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "agent.uninstall.run",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "apply_skill_group_exclusive_mount",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "apply_skill_group_mount",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "asset.list",
        tauri_command: Some("list_assets"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter.list",
        tauri_command: Some("list_conversation_adapters"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter.register",
        tauri_command: Some("register_conversation_adapter"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter.runtime-status",
        tauri_command: Some("list_conversation_adapter_runtime_statuses"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter.scaffold",
        tauri_command: Some("scaffold_conversation_adapter"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter.try-run",
        tauri_command: Some("try_run_conversation_adapter"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter.unregister",
        tauri_command: Some("unregister_conversation_adapter"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter.validate",
        tauri_command: Some("validate_conversation_adapter"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.catalog",
        tauri_command: Some("list_conversation_adapter_packages"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.check_updates",
        tauri_command: Some("check_conversation_adapter_package_updates"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.delete_version",
        tauri_command: Some("delete_conversation_adapter_package_version"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.inspect",
        tauri_command: Some("inspect_conversation_adapter_package"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.install",
        tauri_command: Some("install_conversation_adapter_package"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.installed_versions",
        tauri_command: Some("list_installed_conversation_adapter_package_versions"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.prepare_change",
        tauri_command: Some("prepare_conversation_adapter_package_change"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.refresh_catalogs",
        tauri_command: Some("refresh_conversation_adapter_catalogs"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.register_local",
        tauri_command: Some("register_conversation_adapter_local"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.releases",
        tauri_command: Some("list_conversation_adapter_package_releases"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.rollback",
        tauri_command: Some("rollback_conversation_adapter_package_version"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.set_update_policy",
        tauri_command: Some("set_conversation_adapter_package_update_policy"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.switch_version",
        tauri_command: Some("switch_conversation_adapter_package_version"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.uninstall",
        tauri_command: Some("uninstall_conversation_adapter_package"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.update",
        tauri_command: Some("update_conversation_adapter_package"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.adapter_package.upgrade_workspace",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "conversation.block.get",
        tauri_command: Some("get_conversation_block"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.block.list",
        tauri_command: Some("list_conversation_blocks"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.card.translation.connection-test",
        tauri_command: Some("test_conversation_translation_connection"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.card.translation.model-list",
        tauri_command: Some("list_conversation_translation_models"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.card.translation.opencode-run",
        tauri_command: Some("translate_conversation_card_with_opencode"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.card.translation.opencode-status",
        tauri_command: Some("check_opencode_translation_availability"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.card.translation.run",
        tauri_command: Some("translate_conversation_card"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.command_projection.project",
        tauri_command: Some("project_conversation_command_parts"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.data.audit",
        tauri_command: Some("audit_conversation_data"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.data.repair",
        tauri_command: Some("repair_conversation_data"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.data.rollback",
        tauri_command: Some("rollback_conversation_data"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.part.translation.update",
        tauri_command: Some("update_conversation_part_translation"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.question.get",
        tauri_command: Some("get_conversation_question"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.question.list",
        tauri_command: Some("list_conversation_questions"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.question.merge",
        tauri_command: Some("merge_conversation_questions"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.question.split",
        tauri_command: Some("split_conversation_question"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.script.catalog",
        tauri_command: Some("list_conversation_script_catalog"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.script.install",
        tauri_command: Some("install_conversation_script"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.search",
        tauri_command: Some("search_conversation_records"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.search.incremental",
        tauri_command: Some("search_recent_incremental_conversation_records"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.search.index.rebuild",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "conversation.search.index.status",
        tauri_command: Some("get_conversation_search_index_status"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.session.export",
        tauri_command: Some("export_conversation_session"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.session.get",
        tauri_command: Some("get_conversation_session"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.session.list",
        tauri_command: Some("list_conversation_sessions"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.source.add",
        tauri_command: Some("upsert_conversation_source"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.source.disable",
        tauri_command: Some("disable_conversation_source"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.source.list",
        tauri_command: Some("list_conversation_sources"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.source.update",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "conversation.sync",
        tauri_command: Some("sync_conversations"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.web-record.export",
        tauri_command: Some("export_web_record_session"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.web-record.get",
        tauri_command: Some("get_web_record_session"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "conversation.web-record.list",
        tauri_command: Some("list_web_record_sessions"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "create_plan",
        tauri_command: Some("create_plan"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "create_profile",
        tauri_command: Some("create_profile"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "create_skill_group",
        tauri_command: Some("create_skill_group"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "create_source",
        tauri_command: Some("create_source"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "delete_profile",
        tauri_command: Some("delete_profile"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "delete_skill_group",
        tauri_command: Some("delete_skill_group"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "doctor.run",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "execute_plan",
        tauri_command: Some("execute_plan"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "get_navigation_model",
        tauri_command: Some("get_navigation_model"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "get_skill_backup_settings",
        tauri_command: Some("get_skill_backup_settings"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "list_app_shortcut_settings",
        tauri_command: Some("list_app_shortcut_settings"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "list_app_shortcuts",
        tauri_command: Some("list_app_shortcuts"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "list_asset_mount_statuses",
        tauri_command: Some("list_asset_mount_statuses"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "list_asset_mounts",
        tauri_command: Some("list_asset_mounts"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "list_skill_sources",
        tauri_command: Some("list_skill_sources"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "logs_get_snapshot",
        tauri_command: Some("logs_get_snapshot"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "logs_open_log_directory",
        tauri_command: Some("logs_open_log_directory"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "logs_write_operation",
        tauri_command: Some("logs_write_operation"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.candidate.accept",
        tauri_command: Some("accept_memory_candidate"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.candidate.reject",
        tauri_command: Some("reject_memory_candidate"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.dream.archive",
        tauri_command: Some("archive_memory_dream_note"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.dream.get",
        tauri_command: Some("get_memory_dream_note"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.dream.list",
        tauri_command: Some("list_memory_dream_notes"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.dream.preview",
        tauri_command: Some("preview_memory_dream"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.dream.promote",
        tauri_command: Some("promote_memory_dream_note"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.dream.run",
        tauri_command: Some("run_memory_dream"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.dream.status",
        tauri_command: Some("memory_dream_status"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.item.archive",
        tauri_command: Some("archive_memory_item"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.item.create",
        tauri_command: Some("create_memory_item"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.item.get",
        tauri_command: Some("get_memory_item"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.item.list",
        tauri_command: Some("list_memory_items"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.item.update",
        tauri_command: Some("update_memory_item"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.overview",
        tauri_command: Some("memory_overview"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.recall.preview",
        tauri_command: Some("preview_memory_recall"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.recall.run",
        tauri_command: Some("run_memory_recall"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.recent.event.target",
        tauri_command: Some("get_memory_recent_event_target"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.recent.list",
        tauri_command: Some("list_memory_recent"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "memory.verify",
        tauri_command: Some("verify_memory"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "mount_asset_mount",
        tauri_command: Some("mount_asset_mount"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "overview.get",
        tauri_command: Some("get_app_overview"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "preview_skill_group_exclusive_mount",
        tauri_command: Some("preview_skill_group_exclusive_mount"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "profile.list",
        tauri_command: Some("list_profiles"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "prompt.optimization.availability",
        tauri_command: Some("check_prompt_optimization_availability"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "prompt.optimization.run",
        tauri_command: Some("optimize_prompt"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "refresh_asset_mount_statuses",
        tauri_command: Some("refresh_asset_mount_statuses"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "reveal_path",
        tauri_command: Some("reveal_path"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "scan_skill_sources",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "schema.get",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "schema.list",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "set_asset_mount",
        tauri_command: Some("set_asset_mount"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "set_skill_group_manual_members",
        tauri_command: Some("set_skill_group_manual_members"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "settings.get",
        tauri_command: Some("get_app_settings"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "settings.save",
        tauri_command: Some("save_app_settings"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.acquire",
        tauri_command: Some("acquire_skill"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.backup",
        tauri_command: Some("backup_skill"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.backup.batch",
        tauri_command: Some("backup_skills"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.delete",
        tauri_command: Some("delete_asset"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.group.create",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.delete",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.exclusive.apply",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.exclusive.preview",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.get",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.list",
        tauri_command: Some("list_skill_groups"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.group.members.set",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.mount",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.unmount",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.group.update",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.import",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.list",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.mount",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "skill.remote.check",
        tauri_command: Some("check_skill_remote_sources"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.remote.list",
        tauri_command: Some("list_skill_remote_sources"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.search",
        tauri_command: Some("search_skills"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "skill.unmount",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "source.add",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "source.list",
        tauri_command: Some("list_sources"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "source.remove",
        tauri_command: Some("delete_source"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "source.scan",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "start_conversation_search_index_rebuild",
        tauri_command: Some("start_conversation_search_index_rebuild"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "system.version",
        tauri_command: None,
        note: Some("engine-only capability"),
    },
    SurfaceMapping {
        canonical_method: "target.catalog.list",
        tauri_command: Some("list_target_profile_descriptors"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "target.catalog.refresh",
        tauri_command: Some("refresh_target_profile_descriptors"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.create",
        tauri_command: Some("create_team"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.delete",
        tauri_command: Some("delete_team"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.get",
        tauri_command: Some("get_team"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.leader.chat",
        tauri_command: Some("team_leader_chat"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.list",
        tauri_command: Some("list_teams"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.mailbox.read",
        tauri_command: Some("team_mailbox_read"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.mailbox.send",
        tauri_command: Some("team_mailbox_send"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.cancel",
        tauri_command: Some("team_run_cancel"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.confirm",
        tauri_command: Some("team_run_confirm"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.draft",
        tauri_command: Some("team_run_draft"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.get",
        tauri_command: Some("team_run_get"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.latest",
        tauri_command: Some("team_run_latest"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.restore",
        tauri_command: Some("team_run_restore"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.review",
        tauri_command: Some("team_run_review"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.task",
        tauri_command: Some("team_run_task"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.run.tasks",
        tauri_command: Some("list_team_run_tasks"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.task.update",
        tauri_command: Some("team_task_update"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.tool.credential.issue",
        tauri_command: Some("team_tool_credential_issue"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.tool.mailbox.read",
        tauri_command: Some("team_tool_mailbox_read"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.tool.mailbox.send",
        tauri_command: Some("team_tool_mailbox_send"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.tool.task.update",
        tauri_command: Some("team_tool_task_update"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.tool.tasks",
        tauri_command: Some("team_tool_tasks"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "team.update",
        tauri_command: Some("update_team"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "tenant.active",
        tauri_command: Some("get_active_tenant"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "tenant.create",
        tauri_command: Some("create_tenant"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "tenant.list",
        tauri_command: Some("list_tenants"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "tenant.switch",
        tauri_command: Some("switch_tenant"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "toggle_asset_mount",
        tauri_command: Some("toggle_asset_mount"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "unmount_asset_mount",
        tauri_command: Some("unmount_asset_mount"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "update_app_shortcuts",
        tauri_command: Some("update_app_shortcuts"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "update_asset_description",
        tauri_command: Some("update_asset_description"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "update_navigation_model",
        tauri_command: Some("update_navigation_model"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "update_profile",
        tauri_command: Some("update_profile"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "update_skill_backup_settings",
        tauri_command: Some("update_skill_backup_settings"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "update_skill_group",
        tauri_command: Some("update_skill_group"),
        note: None,
    },
    SurfaceMapping {
        canonical_method: "update_source",
        tauri_command: Some("update_source"),
        note: None,
    },
];
