//! Engine 命令注册表：Catalog 领域

use super::dispatch::*;
use super::types::*;
use crate::adapters::engine::protocol;
use crate::backend::application::AppService;
use crate::{command, param};
use serde_json::{json, Value};

pub(super) const COMMANDS: &[CommandSpec] = &[
    command!(
        "source.list",
        "source.list",
        "List registered asset sources",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_sources().await,
        &[],
        Some("assetiweave-cli source list")
    ),
    command!(
        "source.add",
        "source.add",
        "Add a source with CLI-oriented options",
        Write,
        Friendly,
        true,
        crate::backend::application::SourceAddParams,
        ServiceAsync => |service, params| service.add_source_with_options(params).await,
        &[
            param!("name", "Source display name"),
            param!("kind", "Source kind"),
            param!("root_path", "Source root directory", ["rootPath"]),
            param!("scanner_kind", "Scanner kind", ["scannerKind"]),
            param!("source_origin", "Source origin", ["sourceOrigin"]),
            param!("include_globs", "Include glob patterns", ["includeGlobs"]),
            param!("exclude_globs", "Exclude glob patterns", ["excludeGlobs"]),
            param!("default_kind", "Default asset kind", ["defaultKind"]),
            param!("enabled", "Whether the source is enabled"),
            param!("priority", "Source priority"),
            param!("repo_root", "Repository root", ["repoRoot"]),
            param!("scan_root", "Relative scan root", ["scanRoot"]),
            param!(
                "origin_app_kind",
                "Origin application kind",
                ["originAppKind"]
            ),
            param!("dry_run", "Preview without persisting", ["dryRun"]),
        ],
        Some("assetiweave-cli source add --name <name> --path <path>")
    ),
    command!(
        "source.remove",
        "source.remove",
        "Remove a source registration",
        HighRiskWrite,
        Friendly,
        true,
        crate::backend::application::SourceRemoveParams,
        ServiceAsync => |service, params| service.remove_source(params).await,
        &[
            param!("id", "Source identifier"),
            param!("dry_run", "Preview without removing", ["dryRun"]),
            param!("yes", "Confirm the destructive operation"),
        ],
        Some("assetiweave-cli source remove <source-id> --yes")
    ),
    command!(
        "source.scan",
        "source.scan",
        "Scan registered sources",
        Write,
        Friendly,
        true,
        crate::backend::application::SourceScanParams,
        ServiceAsync => |service, params| service.scan_sources(params).await,
        &[
            param!("kind", "Optional asset kind filter"),
            param!(
                "dry_run",
                "Return current assets without scanning",
                ["dryRun"]
            ),
        ],
        Some("assetiweave-cli source scan")
    ),
    command!(
        "asset.list",
        "asset.list",
        "List catalog assets",
        Read,
        Friendly,
        false,
        crate::backend::application::ListAssetsParams,
        ServiceAsync => |service, params| service.list_assets(params).await,
        &[param!("kind", "Optional asset kind filter")],
        Some("assetiweave-cli asset list")
    ),
    command!(
        "skill.list",
        "skill.list",
        "List Skill assets",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_skills().await,
        &[],
        Some("assetiweave-cli skill list")
    ),
    command!(
        "skill.import",
        "skill.import",
        "Import a Skill into the AssetIWeave backup library",
        Write,
        Friendly,
        true,
        crate::backend::application::ImportSkillParams,
        ServiceAsync => |service, params| service.import_skill(params).await,
        &[
            param!("from", "Directory containing SKILL.md"),
            param!("name", "Optional imported Skill name"),
            param!("dry_run", "Preview without copying", ["dryRun"]),
        ],
        Some("assetiweave-cli skill import --from <dir>")
    ),
    command!(
        "skill.search",
        "skill.search",
        "Search internet providers for Skill candidates",
        Read,
        Friendly,
        false,
        crate::backend::application::SkillSearchParams,
        Service => |service, params| service.search_skills(params),
        &[
            param!("query", "Skill search query"),
            param!("provider", "Search provider"),
            param!("limit", "Maximum candidate count"),
        ],
        Some("assetiweave-cli skill search --query <query>")
    ),
    command!(
        "skill.acquire",
        "skill.acquire",
        "Download and import a Skill candidate",
        HighRiskWrite,
        Friendly,
        true,
        crate::backend::application::SkillAcquireParams,
        ServiceAsync => |service, params| service.acquire_skill(params).await,
        &[
            param!("url", "GitHub repository or tree URL"),
            param!("branch", "Git branch override"),
            param!("path", "Skill directory path inside the repository"),
            param!("name", "Imported Skill name"),
            param!("dry_run", "Preview without cloning or importing", ["dryRun"]),
            param!("yes", "Confirm download and import"),
        ],
        Some("assetiweave-cli skill acquire --url <github-url> --yes")
    ),
    command!(
        "skill.remote.list",
        "skill.remote.list",
        "List acquired Skill remote sources",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_skill_remote_sources().await,
        &[],
        Some("assetiweave-cli skill remote list")
    ),
    command!(
        "skill.remote.check",
        "skill.remote.check",
        "Check acquired Skill remote sources for drift",
        Write,
        Friendly,
        false,
        crate::backend::application::SkillRemoteCheckParams,
        ServiceAsync => |service, params| service.check_skill_remote_sources(params).await,
        &[param!("asset_id", "Optional asset identifier", ["assetId"])],
        Some("assetiweave-cli skill remote check [asset-id]")
    ),
    command!(
        "skill.backup",
        "skill.backup",
        "Back up a Skill into the AssetIWeave library",
        Write,
        Friendly,
        false,
        crate::backend::application::RequiredAssetIdParams,
        ServiceAsync => |service, params| service.backup_skill(params.asset_id).await,
        &[param!("asset_id", "Asset identifier", ["assetId"])],
        Some("assetiweave-cli skill backup <asset-id>")
    ),
    command!(
        "skill.delete",
        "skill.delete",
        "Delete an AssetIWeave backup-library Skill",
        HighRiskWrite,
        Friendly,
        true,
        crate::backend::application::AssetRefParams,
        ServiceAsync => |service, params| service.delete_skill(params).await,
        &[
            param!("asset_ref", "Asset identifier or name", ["assetRef"]),
            param!("profile_id", "Optional target profile", ["profileId"]),
            param!("dry_run", "Preview without deleting", ["dryRun"]),
            param!("yes", "Confirm the destructive operation"),
            param!("unmount", "Unmount managed targets before deleting"),
        ],
        Some("assetiweave-cli skill delete <asset-ref> --yes")
    ),
    command!(
        "skill.mount",
        "skill.mount",
        "Mount a Skill to a target profile",
        Write,
        Friendly,
        true,
        crate::backend::application::AssetRefParams,
        ServiceAsync => |service, params| service.mount_skill(params, true).await,
        &[
            param!("asset_ref", "Asset identifier or name", ["assetRef"]),
            param!("profile_id", "Target profile identifier", ["profileId"]),
            param!("dry_run", "Preview without mounting", ["dryRun"]),
        ],
        Some("assetiweave-cli skill mount <asset-ref> --profile <profile-id>")
    ),
    command!(
        "skill.unmount",
        "skill.unmount",
        "Unmount a Skill from a target profile",
        Write,
        Friendly,
        true,
        crate::backend::application::AssetRefParams,
        ServiceAsync => |service, params| service.mount_skill(params, false).await,
        &[
            param!("asset_ref", "Asset identifier or name", ["assetRef"]),
            param!("profile_id", "Target profile identifier", ["profileId"]),
            param!("dry_run", "Preview without unmounting", ["dryRun"]),
        ],
        Some("assetiweave-cli skill unmount <asset-ref> --profile <profile-id>")
    ),
    command!(
        "skill.group.list",
        "skill.group.list",
        "List Skill groups",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_skill_groups().await,
        &[],
        Some("assetiweave-cli skill group list")
    ),
    command!(
        "skill.group.get",
        "skill.group.get",
        "Show a Skill group with resolved members",
        Read,
        Friendly,
        false,
        crate::backend::application::GroupIdParams,
        ServiceAsync => |service, params| service.get_skill_group(params.group_id).await,
        &[param!("group_id", "Skill group identifier", ["groupId"])],
        Some("assetiweave-cli skill group show <group-id>")
    ),
    command!(
        "skill.group.create",
        "skill.group.create",
        "Create a Skill group",
        Write,
        Friendly,
        false,
        crate::backend::application::CreateSkillGroupParams,
        ServiceAsync => |service, params| service.create_skill_group(params.input).await,
        &[param!("input", "Skill group input")],
        Some("assetiweave-cli skill group create --name <name>")
    ),
    command!(
        "skill.group.update",
        "skill.group.update",
        "Update a Skill group",
        Write,
        Friendly,
        false,
        crate::backend::application::UpdateSkillGroupParams,
        ServiceAsync => |service, params| service.update_skill_group(params.group).await,
        &[param!("group", "Complete Skill group record")],
        Some("assetiweave-cli skill group update <group-id> --json <json>")
    ),
    command!(
        "skill.group.delete",
        "skill.group.delete",
        "Delete a Skill group",
        HighRiskWrite,
        Friendly,
        false,
        crate::backend::application::GroupIdParams,
        ServiceAsync => |service, params| service.delete_skill_group(params.group_id).await,
        &[param!("group_id", "Skill group identifier", ["groupId"])],
        Some("assetiweave-cli skill group delete <group-id> --yes")
    ),
    command!(
        "skill.group.members.set",
        "skill.group.members.set",
        "Replace the manual members of a Skill group",
        Write,
        Friendly,
        false,
        crate::backend::application::SetSkillGroupManualMembersParams,
        ServiceAsync => |service, params| service.set_skill_group_manual_members(params.group_id, params.asset_ids).await,
        &[
            param!("group_id", "Skill group identifier", ["groupId"]),
            param!("asset_ids", "Manual member asset identifiers", ["assetIds"]),
        ],
        Some("assetiweave-cli skill group members set <group-id> --asset <asset-id>")
    ),
    command!(
        "skill.group.mount",
        "skill.group.mount",
        "Mount a Skill group to a target profile",
        Write,
        Friendly,
        true,
        crate::backend::application::SkillGroupMountParams,
        ServiceAsync => |service, params| service.mount_skill_group(params, true).await,
        &[
            param!("group_id", "Skill group identifier", ["groupId"]),
            param!("profile_id", "Target profile identifier", ["profileId"]),
            param!("dry_run", "Preview without mounting", ["dryRun"]),
        ],
        Some("assetiweave-cli skill group mount <group-id> --profile <profile-id>")
    ),
    command!(
        "skill.group.unmount",
        "skill.group.unmount",
        "Unmount a Skill group from a target profile",
        HighRiskWrite,
        Friendly,
        true,
        crate::backend::application::SkillGroupMountParams,
        ServiceAsync => |service, params| service.mount_skill_group(params, false).await,
        &[
            param!("group_id", "Skill group identifier", ["groupId"]),
            param!("profile_id", "Target profile identifier", ["profileId"]),
            param!("dry_run", "Preview without unmounting", ["dryRun"]),
            param!("yes", "Confirm the destructive operation"),
        ],
        Some("assetiweave-cli skill group unmount <group-id> --profile <profile-id> --yes")
    ),
    command!(
        "skill.group.exclusive.preview",
        "skill.group.exclusive.preview",
        "Preview an exclusive Skill group mount operation",
        Read,
        Friendly,
        false,
        crate::backend::application::SkillGroupExclusiveMountParams,
        ServiceAsync => |service, params| service.preview_skill_group_exclusive_mount(params.input).await,
        &[param!("input", "Exclusive mount input")],
        Some("assetiweave-cli skill group exclusive preview --group <group-id> --profile <profile-id>")
    ),
    command!(
        "skill.group.exclusive.apply",
        "skill.group.exclusive.apply",
        "Apply an exclusive Skill group mount operation",
        HighRiskWrite,
        Friendly,
        false,
        crate::backend::application::SkillGroupExclusiveMountParams,
        ServiceAsync => |service, params| service.apply_skill_group_exclusive_mount(params.input).await,
        &[param!("input", "Exclusive mount input")],
        Some("assetiweave-cli skill group exclusive apply --group <group-id> --profile <profile-id> --yes")
    ),
    command!(
        "list_assets",
        "asset.list",
        "List catalog assets",
        Read,
        App,
        false,
        crate::backend::application::ListAssetsParams,
        ServiceAsync => |service, params| service.list_assets(params).await,
        &[param!("kind", "Optional asset kind filter")],
        None
    ),
    command!(
        "get_skill_backup_settings",
        "get_skill_backup_settings",
        "Get Skill backup library settings",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.get_skill_backup_settings().await,
        &[],
        None
    ),
    command!(
        "update_skill_backup_settings",
        "update_skill_backup_settings",
        "Update and optionally migrate the Skill backup library",
        HighRiskWrite,
        App,
        false,
        crate::backend::application::UpdateSkillBackupSettingsParams,
        ServiceAsync => |service, params| service.update_skill_backup_settings(params).await,
        &[
            param!("root_path", "Backup library root path", ["rootPath"]),
            param!("migrate", "Migrate existing backup files"),
        ],
        None
    ),
    command!(
        "backup_skill",
        "skill.backup",
        "Back up a Skill into the AssetIWeave library",
        Write,
        App,
        false,
        crate::backend::application::RequiredAssetIdParams,
        ServiceAsync => |service, params| service.backup_skill(params.asset_id).await,
        &[param!("asset_id", "Asset identifier", ["assetId"])],
        None
    ),
    command!(
        "backup_skills",
        "skill.backup.batch",
        "Start or run a batch Skill backup",
        Write,
        App,
        false,
        crate::backend::application::SkillBackupTaskParams,
        ServiceAsync => |service, params| service.backup_skills(params.asset_ids).await,
        &[param!("asset_ids", "Asset identifiers", ["assetIds"])],
        None
    ),
    command!(
        "search_skills",
        "skill.search",
        "Search internet providers for Skill candidates",
        Read,
        App,
        false,
        crate::backend::application::SkillSearchParams,
        Service => |service, params| service.search_skills(params),
        &[
            param!("query", "Skill search query"),
            param!("provider", "Search provider"),
            param!("limit", "Maximum candidate count"),
        ],
        Some("assetiweave-cli skill search --query <query>")
    ),
    command!(
        "acquire_skill",
        "skill.acquire",
        "Download and import a Skill candidate",
        HighRiskWrite,
        App,
        true,
        crate::backend::application::SkillAcquireParams,
        ServiceAsync => |service, params| service.acquire_skill(params).await,
        &[
            param!("url", "GitHub repository or tree URL"),
            param!("branch", "Git branch override"),
            param!("path", "Skill directory path inside the repository"),
            param!("name", "Imported Skill name"),
            param!("dry_run", "Preview without cloning or importing", ["dryRun"]),
            param!("yes", "Confirm download and import"),
        ],
        Some("assetiweave-cli skill acquire --url <github-url> --yes")
    ),
    command!(
        "list_skill_remote_sources",
        "skill.remote.list",
        "List acquired Skill remote sources",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_skill_remote_sources().await,
        &[],
        Some("assetiweave-cli skill remote list")
    ),
    command!(
        "check_skill_remote_sources",
        "skill.remote.check",
        "Check acquired Skill remote sources for drift",
        Write,
        App,
        false,
        crate::backend::application::SkillRemoteCheckParams,
        ServiceAsync => |service, params| service.check_skill_remote_sources(params).await,
        &[param!("asset_id", "Optional asset identifier", ["assetId"])],
        Some("assetiweave-cli skill remote check [asset-id]")
    ),
    command!(
        "list_sources",
        "source.list",
        "List registered asset sources",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_sources().await,
        &[],
        None
    ),
    command!(
        "list_skill_sources",
        "list_skill_sources",
        "List registered Skill sources",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_skill_sources().await,
        &[],
        None
    ),
    command!(
        "create_source",
        "create_source",
        "Create an asset source",
        Write,
        App,
        false,
        crate::backend::application::CreateSourceParams,
        ServiceAsync => |service, params| service.add_source(params.source).await,
        &[param!("source", "Source input")],
        None
    ),
    command!(
        "update_source",
        "update_source",
        "Update an asset source",
        Write,
        App,
        false,
        crate::backend::application::UpdateSourceParams,
        ServiceAsync => |service, params| service.update_source(params.source).await,
        &[param!("source", "Complete source record")],
        None
    ),
    command!(
        "delete_source",
        "source.remove",
        "Delete an asset source registration",
        HighRiskWrite,
        App,
        false,
        crate::backend::application::IdParams,
        ServiceAsync => |service, params| service.delete_source(params.id).await,
        &[param!("id", "Source identifier")],
        None
    ),
    command!(
        "update_asset_description",
        "update_asset_description",
        "Update an asset description",
        Write,
        App,
        false,
        crate::backend::application::UpdateAssetDescriptionParams,
        ServiceAsync => |service, params| service.update_asset_description(params.asset_id, params.description).await,
        &[
            param!("asset_id", "Asset identifier", ["assetId"]),
            param!("description", "New description"),
        ],
        None
    ),
    command!(
        "delete_asset",
        "skill.delete",
        "Delete an AssetIWeave-managed asset",
        HighRiskWrite,
        App,
        false,
        crate::backend::application::DeleteAssetParams,
        ServiceAsync => |service, params| service.delete_asset(params.asset_id, params.unmount).await,
        &[
            param!("asset_id", "Asset identifier", ["assetId"]),
            param!("unmount", "Unmount managed targets before deleting"),
        ],
        None
    ),
    command!(
        "scan_sources",
        "source.scan",
        "Scan registered sources",
        Write,
        App,
        true,
        crate::backend::application::SourceScanParams,
        ServiceAsync => |service, params| service.scan_sources(params).await,
        &[
            param!("kind", "Optional asset kind filter"),
            param!(
                "dry_run",
                "Return current assets without scanning",
                ["dryRun"]
            ),
        ],
        None
    ),
    command!(
        "scan_skill_sources",
        "scan_skill_sources",
        "Scan registered Skill sources",
        Write,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.scan_skill_sources().await,
        &[],
        None
    ),
];
