//! Engine 命令注册表：Memory 领域

use super::dispatch::*;
use super::types::*;
use crate::adapters::engine::protocol;
use crate::backend::application::AppService;
use crate::{command, param};
use serde_json::{json, Value};

pub(super) const COMMANDS: &[CommandSpec] = &[
    command!(
        "memory.recent.snapshot.get",
        "memory.recent.snapshot.get",
        "Get the current tenant's structured recent memory state and last-success snapshot",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.get_recent_memory_snapshot().await,
        &[],
        Some("assetiweave-cli memory recent get"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.context.resolve",
        "memory.context.resolve",
        "Resolve the bounded compiled Memory context for an optional project and query",
        Read,
        Friendly,
        false,
        crate::backend::application::MemoryContextResolveParams,
        ServiceAsync => |service, params| service.resolve_memory_context(params).await,
        &[
            param!("project_path", "Optional registered project path", ["projectPath"]),
            param!("query", "Optional query for relevance ordering"),
            param!("token_budget", "Maximum context token budget", ["tokenBudget"]),
        ],
        Some("assetiweave-cli memory context resolve"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.project.get",
        "memory.project.get",
        "Get the current SQLite L2 project Memory view and source availability",
        Read,
        Friendly,
        false,
        crate::backend::application::MemoryProjectGetParams,
        ServiceAsync => |service, params| service.get_memory_project(params).await,
        &[param!("project_path", "Registered project path", ["projectPath"])],
        Some("assetiweave-cli memory project get <project-path>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.rebuild",
        "memory.rebuild",
        "Queue a Memory maintenance rebuild for recent, project, global, all, or projection repair",
        Write,
        Friendly,
        false,
        crate::backend::application::MemoryScopeRebuildParams,
        ServiceAsync => |service, params| service.rebuild_memory_scope(params).await,
        &[
            param!("scope", "Legacy optional Memory scope"),
            param!("target", "Rebuild target: recent, project, global, or all"),
            param!("project_path", "Project path required for project target", ["projectPath"]),
            param!("reason", "Rebuild reason: manual, migration, or projection_repair"),
        ],
        Some("assetiweave-cli memory rebuild --target <target>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.task.list",
        "memory.task.list",
        "List Memory background tasks",
        Read,
        Friendly,
        false,
        crate::backend::application::MemoryTaskListParams,
        Service => |service, params| service.list_memory_task_views(params),
        &[param!("active_only", "Only active tasks", ["activeOnly"])],
        Some("assetiweave-cli memory task list"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.task.get",
        "memory.task.get",
        "Get one Memory background task",
        Read,
        Friendly,
        false,
        crate::backend::application::MemoryTaskGetParams,
        Service => |service, params| service.get_memory_task_view(params),
        &[param!("task_id", "Memory task identifier", ["taskId"])],
        Some("assetiweave-cli memory task get <task-id>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.task.cancel",
        "memory.task.cancel",
        "Cancel one active Memory background task",
        Write,
        Friendly,
        false,
        crate::backend::application::MemoryTaskGetParams,
        Service => |service, params| service.cancel_memory_task_view(params),
        &[param!("task_id", "Memory task identifier", ["taskId"])],
        Some("assetiweave-cli memory task cancel <task-id>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.task.retry",
        "memory.task.retry",
        "Retry one failed Memory background task",
        Write,
        Friendly,
        false,
        crate::backend::application::MemoryTaskRetryParams,
        ServiceAsync => |service, params| service.retry_memory_task(params).await,
        &[param!("task_id", "Memory task identifier", ["taskId"])],
        Some("assetiweave-cli memory task retry <task-id>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.recall.search",
        "memory.recall.search",
        "Search Memory source content with deterministic hybrid ranking",
        Read,
        Friendly,
        false,
        crate::backend::application::MemoryRecallSearchParams,
        ServiceAsync => |service, params| service.search_memory_recall(params).await,
        &[
            param!("query", "Search query"),
            param!("scope", "Optional Memory scope"),
            param!("limit", "Maximum number of hits"),
            param!("offset", "Pagination offset"),
        ],
        Some("assetiweave-cli memory recall search --query <query>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.recall.session.create",
        "memory.recall.session.create",
        "Create a persistent Recall session",
        Write,
        Friendly,
        false,
        crate::backend::application::MemoryRecallSessionCreateParams,
        ServiceAsync => |service, params| service.create_memory_recall_session(params).await,
        &[param!("scope", "Optional Memory scope")],
        Some("assetiweave-cli memory recall session create"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.recall.session.get",
        "memory.recall.session.get",
        "Get a persistent Recall session and its turns",
        Read,
        Friendly,
        false,
        crate::backend::application::MemoryRecallSessionGetParams,
        ServiceAsync => |service, params| service.get_memory_recall_session(params).await,
        &[param!("session_id", "Recall session identifier", ["sessionId"])],
        Some("assetiweave-cli memory recall session get <session-id>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.recall.turn.send",
        "memory.recall.turn.send",
        "Queue one Recall turn in a persistent session",
        Write,
        Friendly,
        false,
        crate::backend::application::MemoryRecallTurnSendParams,
        ServiceAsync => |service, params| service.send_memory_recall_turn(params).await,
        &[
            param!("session_id", "Recall session identifier", ["sessionId"]),
            param!("query", "Recall question"),
        ],
        Some("assetiweave-cli memory recall turn send <session-id> --query <query>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "memory.recall.turn.cancel",
        "memory.recall.turn.cancel",
        "Cancel the active Recall turn",
        Write,
        Friendly,
        false,
        crate::backend::application::MemoryRecallTurnCancelParams,
        ServiceAsync => |service, params| service.cancel_memory_recall_turn(params).await,
        &[param!("turn_id", "Recall turn identifier", ["turnId"])],
        Some("assetiweave-cli memory recall turn cancel <turn-id>"),
        since: "0.6.1", deprecated: false
    ),
    command!(
        "get_memory_recent_snapshot",
        "memory.recent.snapshot.get",
        "Get the current tenant's structured recent memory state and last-success snapshot",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.get_recent_memory_snapshot().await,
        &[],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "resolve_memory_context",
        "memory.context.resolve",
        "Resolve the bounded compiled Memory context for an optional project and query",
        Read,
        App,
        false,
        crate::backend::application::MemoryContextResolveParams,
        ServiceAsync => |service, params| service.resolve_memory_context(params).await,
        &[
            param!("project_path", "Optional registered project path", ["projectPath"]),
            param!("query", "Optional query for relevance ordering"),
            param!("token_budget", "Maximum context token budget", ["tokenBudget"]),
        ],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "get_memory_project",
        "memory.project.get",
        "Get the current SQLite L2 project Memory view and source availability",
        Read,
        App,
        false,
        crate::backend::application::MemoryProjectGetParams,
        ServiceAsync => |service, params| service.get_memory_project(params).await,
        &[param!("project_path", "Registered project path", ["projectPath"])],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "rebuild_memory_scope",
        "memory.rebuild",
        "Queue a Memory maintenance rebuild for recent, project, global, all, or projection repair",
        Write,
        App,
        false,
        crate::backend::application::MemoryScopeRebuildParams,
        ServiceAsync => |service, params| service.rebuild_memory_scope(params).await,
        &[
            param!("scope", "Legacy optional Memory scope"),
            param!("target", "Rebuild target: recent, project, global, or all"),
            param!("project_path", "Project path required for project target", ["projectPath"]),
            param!("reason", "Rebuild reason: manual, migration, or projection_repair"),
        ],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "list_memory_public_tasks",
        "memory.task.list",
        "List Memory background tasks",
        Read,
        App,
        false,
        crate::backend::application::MemoryTaskListParams,
        Service => |service, params| service.list_memory_task_views(params),
        &[param!("active_only", "Only active tasks", ["activeOnly"])],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "get_memory_public_task",
        "memory.task.get",
        "Get one Memory background task",
        Read,
        App,
        false,
        crate::backend::application::MemoryTaskGetParams,
        Service => |service, params| service.get_memory_task_view(params),
        &[param!("task_id", "Memory task identifier", ["taskId"])],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "cancel_memory_public_task",
        "memory.task.cancel",
        "Cancel one active Memory background task",
        Write,
        App,
        false,
        crate::backend::application::MemoryTaskGetParams,
        Service => |service, params| service.cancel_memory_task_view(params),
        &[param!("task_id", "Memory task identifier", ["taskId"])],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "retry_memory_public_task",
        "memory.task.retry",
        "Retry one failed Memory background task",
        Write,
        App,
        false,
        crate::backend::application::MemoryTaskRetryParams,
        ServiceAsync => |service, params| service.retry_memory_task(params).await,
        &[param!("task_id", "Memory task identifier", ["taskId"])],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "search_memory_recall",
        "memory.recall.search",
        "Search Memory source content with deterministic hybrid ranking",
        Read,
        App,
        false,
        crate::backend::application::MemoryRecallSearchParams,
        ServiceAsync => |service, params| service.search_memory_recall(params).await,
        &[
            param!("query", "Search query"),
            param!("scope", "Optional Memory scope"),
            param!("limit", "Maximum number of hits"),
            param!("offset", "Pagination offset"),
        ],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "create_memory_recall_session",
        "memory.recall.session.create",
        "Create a persistent Recall session",
        Write,
        App,
        false,
        crate::backend::application::MemoryRecallSessionCreateParams,
        ServiceAsync => |service, params| service.create_memory_recall_session(params).await,
        &[param!("scope", "Optional Memory scope")],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "get_memory_recall_session",
        "memory.recall.session.get",
        "Get a persistent Recall session and its turns",
        Read,
        App,
        false,
        crate::backend::application::MemoryRecallSessionGetParams,
        ServiceAsync => |service, params| service.get_memory_recall_session(params).await,
        &[param!("session_id", "Recall session identifier", ["sessionId"])],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "send_memory_recall_turn",
        "memory.recall.turn.send",
        "Queue one Recall turn in a persistent session",
        Write,
        App,
        false,
        crate::backend::application::MemoryRecallTurnSendParams,
        ServiceAsync => |service, params| service.send_memory_recall_turn(params).await,
        &[
            param!("session_id", "Recall session identifier", ["sessionId"]),
            param!("query", "Recall question"),
        ],
        None,
        since: "0.6.1", deprecated: false
    ),
    command!(
        "cancel_memory_recall_turn",
        "memory.recall.turn.cancel",
        "Cancel the active Recall turn",
        Write,
        App,
        false,
        crate::backend::application::MemoryRecallTurnCancelParams,
        ServiceAsync => |service, params| service.cancel_memory_recall_turn(params).await,
        &[param!("turn_id", "Recall turn identifier", ["turnId"])],
        None,
        since: "0.6.1", deprecated: false
    ),
];
