//! Engine 命令注册表：System 领域

use super::dispatch::*;
use super::types::*;
use crate::adapters::engine::protocol;
use crate::backend::application::AppService;
use crate::{command, param};
use serde_json::{json, Value};

pub(super) const COMMANDS: &[CommandSpec] = &[
    command!(
        "overview.get",
        "overview.get",
        "Get the AssetIWeave overview",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.overview().await,
        &[],
        Some("assetiweave-cli overview")
    ),
    command!(
        "tenant.list",
        "tenant.list",
        "List tenants visible to the current local principal",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_tenants().await,
        &[],
        Some("assetiweave-cli tenant list")
    ),
    command!(
        "tenant.active",
        "tenant.active",
        "Get the active tenant for the current local principal",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.active_tenant().await,
        &[],
        Some("assetiweave-cli tenant active")
    ),
    command!(
        "tenant.create",
        "tenant.create",
        "Create a local workspace tenant for the current principal",
        Write,
        Friendly,
        false,
        crate::backend::application::TenantCreateParams,
        ServiceAsync => |service, params| service.create_tenant(params).await,
        &[
            param!("name", "Tenant display name"),
            param!("slug", "Tenant stable slug"),
            param!("set_active", "Switch to the created tenant", ["setActive"]),
        ],
        Some("assetiweave-cli tenant create <name>")
    ),
    command!(
        "tenant.switch",
        "tenant.switch",
        "Switch the active tenant for subsequent local calls",
        Write,
        Friendly,
        false,
        crate::backend::application::IdParams,
        ServiceAsync => |service, params| service.switch_tenant(params.id).await,
        &[param!("id", "Tenant identifier")],
        Some("assetiweave-cli tenant switch <tenant-id>")
    ),
    command!(
        "doctor.run",
        "doctor.run",
        "Run local AssetIWeave diagnostics",
        Read,
        Friendly,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.run_doctor().await,
        &[],
        Some("assetiweave-cli doctor")
    ),
    command!(
        "system.version",
        "system.version",
        "Show Engine protocol and contract versions",
        Read,
        System,
        false,
        NoParams,
        System => |_params| protocol::version_info(),
        &[],
        Some("assetiweave-cli version")
    ),
    command!(
        "schema.list",
        "schema.list",
        "List engine command contracts",
        Read,
        System,
        false,
        NoParams,
        System => |_params| schema_index(),
        &[],
        Some("assetiweave-cli schema")
    ),
    command!(
        "schema.get",
        "schema.get",
        "Get one engine command contract",
        Read,
        System,
        false,
        SchemaGetParams,
        System => |params| params.method.as_deref().map_or_else(schema_index, schema_get),
        &[param!("method", "Method name to inspect")],
        Some("assetiweave-cli schema <method>")
    ),
    command!(
        "get_app_overview",
        "overview.get",
        "Get the AssetIWeave overview",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.overview().await,
        &[],
        None
    ),
    command!(
        "list_tenants",
        "tenant.list",
        "List tenants visible to the current local principal",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_tenants().await,
        &[],
        None
    ),
    command!(
        "get_active_tenant",
        "tenant.active",
        "Get the active tenant for the current local principal",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.active_tenant().await,
        &[],
        None
    ),
    command!(
        "create_tenant",
        "tenant.create",
        "Create a local workspace tenant for the current principal",
        Write,
        App,
        false,
        crate::backend::application::TenantCreateParams,
        ServiceAsync => |service, params| service.create_tenant(params).await,
        &[
            param!("name", "Tenant display name"),
            param!("slug", "Tenant stable slug"),
            param!("set_active", "Switch to the created tenant", ["setActive"]),
        ],
        None
    ),
    command!(
        "switch_tenant",
        "tenant.switch",
        "Switch the active tenant for subsequent local calls",
        Write,
        App,
        false,
        crate::backend::application::IdParams,
        ServiceAsync => |service, params| service.switch_tenant(params.id).await,
        &[param!("id", "Tenant identifier")],
        None
    ),
    command!(
        "get_app_settings",
        "settings.get",
        "Get the user settings JSON file and managed settings paths",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.get_app_settings().await,
        &[],
        Some("assetiweave-cli settings show")
    ),
    command!(
        "save_app_settings",
        "settings.save",
        "Save the user settings JSON file",
        Write,
        App,
        false,
        crate::backend::application::SaveAppSettingsParams,
        ServiceAsync => |service, params| service.save_app_settings(Value::Object(params.settings.into_iter().collect())).await,
        &[param!("settings", "Normalized application settings object")],
        Some("assetiweave-cli settings save --json <json>")
    ),
    command!(
        "initialize_app_locale_if_unset",
        "settings.locale.initialize",
        "Initialize the application locale if not yet set",
        Write,
        App,
        false,
        crate::backend::application::InitializeAppLocaleParams,
        ServiceAsync => |service, params| service.initialize_app_locale_if_unset(params.locale).await,
        &[param!("locale", "Application locale (zh or en)")],
        None
    ),
    command!(
        "get_navigation_model",
        "get_navigation_model",
        "Get the navigation model",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.navigation_model().await,
        &[],
        None
    ),
    command!(
        "update_navigation_model",
        "update_navigation_model",
        "Update the navigation model",
        Write,
        App,
        false,
        crate::backend::application::UpdateNavigationModelParams,
        ServiceAsync => |service, params| service.update_navigation_model(params.model).await,
        &[param!("model", "Navigation model")],
        None
    ),
    command!(
        "list_app_shortcuts",
        "list_app_shortcuts",
        "List enabled App shortcuts",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_app_shortcuts().await,
        &[],
        None
    ),
    command!(
        "list_app_shortcut_settings",
        "list_app_shortcut_settings",
        "List App shortcut settings",
        Read,
        App,
        false,
        NoParams,
        ServiceAsync => |service, _params| service.list_app_shortcut_settings().await,
        &[],
        None
    ),
    command!(
        "update_app_shortcuts",
        "update_app_shortcuts",
        "Update App shortcut settings",
        Write,
        App,
        false,
        crate::backend::application::UpdateAppShortcutsParams,
        ServiceAsync => |service, params| service.update_app_shortcuts(params.shortcuts).await,
        &[param!("shortcuts", "App shortcut records")],
        None
    ),
    command!(
        "logs_get_snapshot",
        "logs_get_snapshot",
        "Read an AssetIWeave log snapshot",
        Read,
        App,
        false,
        crate::backend::application::LogsGetSnapshotParams,
        Service => |service, params| service.logs_get_snapshot(params.file_name, params.line_limit),
        &[
            param!("file_name", "Optional log file name", ["fileName"]),
            param!("line_limit", "Maximum line count", ["lineLimit"]),
        ],
        None
    ),
    command!(
        "logs_open_log_directory",
        "logs_open_log_directory",
        "Open the AssetIWeave log directory",
        Read,
        App,
        false,
        NoParams,
        Service => |service, _params| service.logs_open_log_directory(),
        &[],
        None
    ),
    command!(
        "logs_write_operation",
        "logs_write_operation",
        "Write a structured AssetIWeave operation log",
        Write,
        App,
        false,
        crate::backend::application::LogsWriteOperationParams,
        Service => |service, params| service.logs_write_operation(params.level, params.operation, params.message, params.fields),
        &[
            param!("level", "Log level"),
            param!("operation", "Operation name"),
            param!("message", "Log message"),
            param!("fields", "Optional structured fields"),
        ],
        None
    ),
    command!(
        "reveal_path",
        "reveal_path",
        "Reveal a local path in the system file manager",
        Read,
        App,
        false,
        RevealPathParams,
        System => |params| crate::adapters::platform::reveal_path(params.path),
        &[param!("path", "Local path to reveal")],
        None
    ),
    command!(
        "list_public_tasks",
        "task.list",
        "List background tasks",
        Read,
        App,
        false,
        crate::backend::application::system::TaskListParams,
        Service => |service, params| service.list_public_tasks(params),
        &[
            param!("tenant_id", "Tenant identifier", ["tenantId"]),
            param!("all_tenants", "Include all tenants", ["allTenants"]),
            param!("active_only", "Only active tasks", ["activeOnly"]),
        ],
        None
    ),
    command!(
        "get_public_task",
        "task.get",
        "Get one background task by ID",
        Read,
        App,
        false,
        crate::backend::application::system::TaskGetParams,
        Service => |service, params| service.get_public_task(params),
        &[param!("task_id", "Task identifier", ["taskId"])],
        None
    ),
    command!(
        "cancel_public_task",
        "task.cancel",
        "Cancel one active background task",
        Write,
        App,
        false,
        crate::backend::application::system::TaskCancelParams,
        Service => |service, params| service.cancel_public_task(params),
        &[param!("task_id", "Task identifier", ["taskId"])],
        None
    ),
    command!(
        "retry_public_task",
        "task.retry",
        "Retry one failed background task",
        Write,
        App,
        false,
        crate::backend::application::system::TaskRetryParams,
        ServiceAsync => |service, params| service.retry_public_task(params).await,
        &[param!("task_id", "Task identifier", ["taskId"])],
        None
    ),
    command!(
        "clear_terminal_tasks",
        "task.clear",
        "Clear terminal background tasks",
        Write,
        App,
        false,
        crate::backend::application::system::TaskClearParams,
        Service => |service, params| service.clear_terminal_tasks(params),
        &[
            param!("tenant_id", "Tenant identifier", ["tenantId"]),
            param!("task_id", "Task identifier", ["taskId"]),
        ],
        None
    ),
];
