export const FAST_SCROLL_ENTER_PX_PER_MS = 1.25;
export const FAST_SCROLL_EXIT_PX_PER_MS = 0.6;
export const SCROLL_IDLE_DELAY_MS = 140;
export const VELOCITY_PREVIOUS_WEIGHT = 0.7;
export const VELOCITY_INSTANT_WEIGHT = 0.3;
