//! Tauri Command 暴露层与 IPC 调用适配模块
//!
//! 该模块包含了所有前端通过 `invoke('plugin:assetiweave|...')` 调用的 Tauri Command 函数实现。
//! 包含应用配置、数据源管理、资产挂载、会话同步与翻译、Memory 以及 CLI 安装等 IPC 交互逻辑。

#[macro_use]
pub(crate) mod agents;
#[macro_use]
pub(crate) mod catalog;
#[macro_use]
pub(crate) mod conversations;
#[macro_use]
pub(crate) mod memory;
#[macro_use]
pub(crate) mod mounting;
#[macro_use]
pub(crate) mod system;

pub(crate) const BASELINE_COMMAND_COUNT: usize = 191;

pub(crate) use self::agents::*;
pub(crate) use self::catalog::*;
pub(crate) use self::conversations::*;
pub(crate) use self::memory::*;
pub(crate) use self::mounting::*;
pub(crate) use self::system::*;

pub(crate) fn command_handler(
) -> impl Fn(::tauri::ipc::Invoke<::tauri::Wry>) -> bool + Send + Sync + 'static {
    ::tauri::generate_handler![
        get_app_overview,
        set_app_window_icon,
        list_tenants,
        get_active_tenant,
        create_tenant,
        switch_tenant,
        get_app_settings,
        save_app_settings,
        initialize_app_locale_if_unset,
        cancel_app_close_prompt,
        complete_app_close,
        list_assets,
        list_source_assets,
        get_memory_recent_snapshot,
        duplicate_memory_generation_skill,
        reset_memory_generation_skill_to_default,
        resolve_memory_context,
        get_memory_project,
        rebuild_memory_scope,
        list_memory_public_tasks,
        get_memory_public_task,
        cancel_memory_public_task,
        retry_memory_public_task,
        search_memory_recall,
        create_memory_recall_session,
        get_memory_recall_session,
        send_memory_recall_turn,
        cancel_memory_recall_turn,
        get_skill_backup_settings,
        update_skill_backup_settings,
        backup_skill,
        backup_skills,
        get_skill_backup_task,
        search_skills,
        start_skill_acquire,
        acquire_skill,
        get_skill_acquire_task,
        list_skill_acquire_tasks,
        cancel_skill_acquire_task,
        list_skill_remote_sources,
        check_skill_remote_sources,
        list_sources,
        list_skill_sources,
        create_source,
        update_source,
        delete_source,
        update_asset_description,
        delete_asset,
        list_profiles,
        list_target_profile_descriptors,
        refresh_target_profile_descriptors,
        create_profile,
        update_profile,
        delete_profile,
        get_navigation_model,
        update_navigation_model,
        list_app_shortcuts,
        list_app_shortcut_settings,
        update_app_shortcuts,
        list_asset_mounts,
        list_asset_mount_statuses,
        refresh_asset_mount_statuses,
        list_skill_groups,
        create_skill_group,
        update_skill_group,
        delete_skill_group,
        set_skill_group_manual_members,
        preview_skill_group_exclusive_mount,
        toggle_asset_mount,
        mount_asset_mount,
        unmount_asset_mount,
        set_asset_mount,
        start_source_scan,
        get_source_scan_task,
        list_source_scan_tasks,
        cancel_source_scan,
        start_batch_mount,
        get_batch_mount_task,
        list_batch_mount_tasks,
        cancel_batch_mount,
        list_conversation_adapters,
        scaffold_conversation_adapter,
        validate_conversation_adapter,
        list_conversation_adapter_runtime_statuses,
        list_agent_catalog,
        list_agent_market,
        inspect_agent_market_item,
        refresh_agent_market,
        get_agent_market_refresh_task,
        list_agent_market_refresh_tasks,
        preview_agent_installation,
        preview_agent_uninstall,
        list_installed_agents,
        get_installed_agent,
        check_agent_runtime,
        get_agent_lifecycle_task,
        list_agent_lifecycle_tasks,
        cancel_agent_lifecycle_task,
        start_agent_installation,
        start_agent_update,
        start_agent_reinstallation,
        start_agent_uninstall,
        enable_agent,
        disable_agent,
        check_agent_connection,
        list_agent_models,
        cancel_agent_model_probe,
        check_opencode_translation_availability,
        check_prompt_optimization_availability,
        translate_conversation_card_with_opencode,
        translate_conversation_card,
        optimize_prompt,
        test_conversation_translation_connection,
        list_conversation_translation_models,
        start_conversation_card_translation,
        get_ai_execution_task,
        list_ai_execution_tasks,
        cancel_ai_execution_task,
        register_conversation_adapter,
        unregister_conversation_adapter,
        try_run_conversation_adapter,
        project_conversation_command_parts,
        list_conversation_sources,
        upsert_conversation_source,
        disable_conversation_source,
        list_conversation_script_catalog,
        register_conversation_adapter_local,
        inspect_conversation_adapter_package,
        prepare_conversation_adapter_package_change,
        list_conversation_adapter_packages,
        list_conversation_adapter_package_releases,
        list_installed_conversation_adapter_package_versions,
        switch_conversation_adapter_package_version,
        rollback_conversation_adapter_package_version,
        delete_conversation_adapter_package_version,
        refresh_conversation_adapter_catalogs,
        check_conversation_adapter_package_updates,
        set_conversation_adapter_package_update_policy,
        install_conversation_adapter_package,
        update_conversation_adapter_package,
        uninstall_conversation_adapter_package,
        get_conversation_adapter_package_task,
        install_conversation_script,
        get_conversation_script_install_task,
        sync_conversations,
        get_conversation_sync_task,
        list_conversation_sync_tasks,
        cancel_conversation_sync,
        get_conversation_usage_dashboard,
        get_conversation_usage_scan_status,
        scan_conversation_usage,
        audit_conversation_data,
        repair_conversation_data,
        get_conversation_data_maintenance_task,
        list_conversation_data_maintenance_tasks,
        cancel_conversation_data_maintenance,
        rollback_conversation_data,
        list_conversation_sessions,
        get_conversation_session,
        get_conversation_session_outline,
        export_conversation_session,
        replay_conversation_session_projection,
        list_web_record_sessions,
        get_web_record_session,
        search_conversation_records,
        search_recent_incremental_conversation_records,
        get_conversation_search_index_status,
        start_conversation_search_index_rebuild,
        get_conversation_search_index_task,
        export_web_record_session,
        list_conversation_questions,
        get_conversation_question,
        list_conversation_blocks,
        get_conversation_block,
        merge_conversation_questions,
        split_conversation_question,
        update_conversation_part_translation,
        create_plan,
        execute_plan,
        get_cli_tools_status,
        install_cli_tools,
        logs_get_snapshot,
        logs_open_log_directory,
        logs_write_operation,
        copy_prompt_card_to_clipboard,
        reveal_path,
        list_public_tasks,
        get_public_task,
        cancel_public_task,
        retry_public_task,
        clear_terminal_tasks,
        agent_session_get
    ]
}

#[cfg(test)]
#[path = "baseline_tests.rs"]
mod baseline_tests;
