#!/usr/bin/env python3
"""Generate and validate the Engine/Tauri surface coverage matrix."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "cli/internal/schema/contract.json"
TAURI_COMMANDS = ROOT / "src-tauri/src/adapters/tauri/commands.rs"
ENGINE_REGISTRY = ROOT / "src-tauri/src/adapters/engine/registry.rs"
EXEMPTIONS = ROOT / "scripts/surface-matrix-exemptions.txt"
MARKDOWN = ROOT / "agent-docs/generated/surface-matrix.md"
RUST = ROOT / "src-tauri/src/adapters/engine/surface_mapping.rs"


def tauri_functions() -> list[str]:
    lines = TAURI_COMMANDS.read_text().splitlines()
    result: list[str] = []
    for index, line in enumerate(lines):
        if "tauri::command" not in line:
            continue
        for candidate in lines[index + 1 : index + 32]:
            match = re.search(r"fn\s+([A-Za-z0-9_]+)\s*\(", candidate)
            if match:
                result.append(match.group(1))
                break
    return result


def registry_methods() -> dict[str, str]:
    text = ENGINE_REGISTRY.read_text()
    return {
        method: canonical
        for method, canonical in re.findall(
            r'command!\(\s*"([^"]+)"\s*,\s*"([^"]+)"', text
        )
    }


def load_exemptions() -> set[str]:
    if not EXEMPTIONS.exists():
        return set()
    return {
        line.strip()
        for line in EXEMPTIONS.read_text().splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }


def render_markdown(rows: list[dict]) -> str:
    lines = [
        "# Engine / Tauri / CLI Surface Matrix",
        "",
        "> Generated by `pnpm gen:surface-matrix`; do not edit by hand.",
        "",
        "| canonical capability | Engine methods (aliases) | CLI verb | Tauri command(s) | risk | confirmation |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| `{canonical}` | {methods} | {cli} | {tauri} | `{risk}` | `{confirmation}` |".format(
                canonical=row["canonical"],
                methods="<br>".join(f"`{value}`" for value in row["methods"])
                or "—",
                cli="<br>".join(f"`{value}`" for value in row["cli"])
                or "—",
                tauri="<br>".join(f"`{value}`" for value in row["tauri"])
                or "—",
                risk=row["risk"],
                confirmation=str(row["confirmation"]).lower(),
            )
        )
    return "\n".join(lines) + "\n"


def render_rust(rows: list[dict]) -> str:
    lines = [
        "//! Generated by scripts/gen-surface-matrix.py; do not edit by hand.",
        "",
        "#![allow(dead_code)]",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub(crate) struct SurfaceMapping {",
        "    pub(crate) canonical_method: &'static str,",
        "    pub(crate) tauri_command: Option<&'static str>,",
        "    pub(crate) note: Option<&'static str>,",
        "}",
        "",
        "pub(crate) static SURFACE_MAPPINGS: &[SurfaceMapping] = &[",
    ]
    for row in rows:
        tauri = row["tauri"][0] if row["tauri"] else None
        note = None if tauri else "engine-only capability"
        lines.extend(
            [
                "    SurfaceMapping {",
                f"        canonical_method: {json.dumps(row['canonical'])},",
                f"        tauri_command: {f'Some({json.dumps(tauri)})' if tauri else 'None'},",
                f"        note: {f'Some({json.dumps(note)})' if note else 'None'},",
                "    },",
            ]
        )
    lines.extend(["];"])
    return "\n".join(lines) + "\n"


def build() -> tuple[str, str, int]:
    contract = json.loads(CONTRACT.read_text())
    commands = contract["commands"]
    canonical_names = {item["canonical_method"] for item in commands}
    methods_by_canonical: dict[str, list[dict]] = {}
    for item in commands:
        methods_by_canonical.setdefault(item["canonical_method"], []).append(item)

    registry = registry_methods()
    tauri = tauri_functions()
    exemptions = load_exemptions()
    unknown_exemptions = exemptions - set(tauri)
    if unknown_exemptions:
        raise SystemExit(f"surface exemptions name missing Tauri commands: {sorted(unknown_exemptions)}")
    missing_tauri = sorted(set(tauri) - set(registry) - exemptions)
    if missing_tauri:
        raise SystemExit("Tauri commands missing SurfaceMapping: " + ", ".join(missing_tauri))
    invalid_canonical = sorted(set(registry.values()) - canonical_names)
    if invalid_canonical:
        raise SystemExit("registry canonical_method missing from contract: " + ", ".join(invalid_canonical))

    tauri_by_canonical: dict[str, list[str]] = {}
    for function in tauri:
        if function in registry:
            tauri_by_canonical.setdefault(registry[function], []).append(function)

    rows: list[dict] = []
    for canonical in sorted(canonical_names):
        items = methods_by_canonical[canonical]
        rows.append(
            {
                "canonical": canonical,
                "methods": sorted(item["method"] for item in items),
                "cli": sorted({item["cli"] for item in items if item.get("cli")}),
                "tauri": sorted(tauri_by_canonical.get(canonical, [])),
                "risk": items[0]["risk"],
                "confirmation": items[0]["confirmation_required"],
            }
        )
    return render_markdown(rows), render_rust(rows), len(exemptions)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    markdown, rust, exemption_count = build()
    if args.check:
        if MARKDOWN.read_text() != markdown or RUST.read_text() != rust:
            print("surface matrix is stale; run pnpm gen:surface-matrix", file=sys.stderr)
            return 1
        print(f"surface matrix is current ({exemption_count} explicit Tauri exemptions)")
        return 0
    MARKDOWN.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN.write_text(markdown)
    RUST.write_text(rust)
    print(f"generated {MARKDOWN} and {RUST} ({exemption_count} explicit Tauri exemptions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
