package schema

const (
	MethodSystemVersion                 = "system.version"
	MethodOverviewGet                   = "overview.get"
	MethodSourceList                    = "source.list"
	MethodSourceAdd                     = "source.add"
	MethodSourceRemove                  = "source.remove"
	MethodSourceScan                    = "source.scan"
	MethodProfileList                   = "profile.list"
	MethodSettingsGet                   = "get_app_settings"
	MethodSettingsSave                  = "save_app_settings"
	MethodAssetList                     = "asset.list"
	MethodSkillList                     = "skill.list"
	MethodSkillImport                   = "skill.import"
	MethodSkillBackup                   = "skill.backup"
	MethodSkillDelete                   = "skill.delete"
	MethodSkillMount                    = "skill.mount"
	MethodSkillUnmount                  = "skill.unmount"
	MethodSkillGroupList                = "skill.group.list"
	MethodSkillGroupMount               = "skill.group.mount"
	MethodSkillGroupUnmount             = "skill.group.unmount"
	MethodConversationAdapterList       = "conversation.adapter.list"
	MethodConversationAdapterScaffold   = "conversation.adapter.scaffold"
	MethodConversationAdapterValidate   = "conversation.adapter.validate"
	MethodConversationAdapterRegister   = "conversation.adapter.register"
	MethodConversationAdapterUnregister = "conversation.adapter.unregister"
	MethodConversationAdapterTryRun     = "conversation.adapter.try-run"
	MethodConversationSourceList        = "conversation.source.list"
	MethodConversationSourceAdd         = "conversation.source.add"
	MethodConversationSourceUpdate      = "conversation.source.update"
	MethodConversationSourceDisable     = "conversation.source.disable"
	MethodConversationSync              = "conversation.sync"
	MethodConversationSessionList       = "conversation.session.list"
	MethodConversationSessionGet        = "conversation.session.get"
	MethodConversationSessionExport     = "conversation.session.export"
	MethodConversationQuestionList      = "conversation.question.list"
	MethodConversationQuestionGet       = "conversation.question.get"
	MethodConversationQuestionMerge     = "conversation.question.merge"
	MethodConversationQuestionSplit     = "conversation.question.split"
	MethodDoctorRun                     = "doctor.run"
	MethodSchemaList                    = "schema.list"
	MethodSchemaGet                     = "schema.get"
)
